import { initialTier, TIERS } from './quality.js';
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
const $=s=>document.querySelector(s);
const titles={build:['WE BUILD IT.|YOU STAY|IN CONTROL.','POSSIBILITY.|TAKES SHAPE.','EVERY LAYER.|CONNECTED.','AN IDEA.|MADE REAL.','YOUR SYSTEM.'],finish:['START WITH|WHAT EXISTS.','FIND THE|MISSING PIECES.','REPAIR.|THEN HARDEN.','READY FOR|THE NEXT STEP.','YOUR SYSTEM.'],automate:['LESS HANDOFF.|MORE FLOW.','MAP THE|MANUAL WORK.','CONNECT.|KEEP CONTROL.','A SYSTEM.|WORKING TOGETHER.','YOUR SYSTEM.']};
const descriptions={build:['From scattered possibility to a system you own.','UI, data, identity and intelligence find their place.','Architecture becomes a connected, inspectable system.','An existing product surface. DaySetGo public demo; illustrative transition.','Built by 1stStep. Organized for your control.'],finish:['Your existing system is the starting point.','An illustrative scan exposes breaks in the architecture.','Missing connections return. Evidence remains part of the system.','A visual release concept, not a claim that your system has passed verification.','Built by 1stStep. Organized for your control.'],automate:['Tools, tasks and people begin disconnected.','Map the handoffs before introducing automation.','Agent and automation nodes connect. Human control stays explicit.','Illustrative orchestration resolving toward an existing product.','Built by 1stStep. Organized for your control.']};
const stages=['ENTRY','PATH','ASSEMBLY','PRODUCT','HANDOFF'];
const requested=new URLSearchParams(location.search).get('quality');
let selected=Object.hasOwn(TIERS,requested)?requested:'auto',tier=selected==='auto'?initialTier():selected;
$('#quality').value=selected;
let path='build',progress=0,stage=-1,scene,staticMode=motionQuery.matches,loading=0;
function update(){progress=Math.min(1,Math.max(0,scrollY/($('#experience').offsetHeight-innerHeight)));$('#timeline').value=Math.round(progress*1000);const next=Math.min(4,Math.floor(progress*4.999));if(next!==stage){stage=next;copy()}scene?.set(progress,path)}
function copy(){const parts=titles[path][stage<0?0:stage].split('|');$('#headline').replaceChildren(...parts.flatMap((part,i)=>{const el=document.createElement(i?'span':'b');el.textContent=part;return i?[document.createElement('br'),el]:[el]}));$('#description').textContent=descriptions[path][Math.max(0,stage)];$('#eyebrow').textContent=`0${stage+1} / ${stages[stage]}`;$('#step').textContent=stages[stage];$('#scene-label').textContent=stage===4?'SOURCE · ACCESS · DATA · DOCS · EVIDENCE → OWNER':path==='automate'?'AUTOMATION · AGENTS · HUMAN CONTROL':'UI · DATA · AUTH · AI · AUTOMATION';$('#cta').hidden=stage!==4;$('.product-caption').hidden=stage!==3;$('#status').textContent=`${path}: ${stages[stage]}. ${descriptions[path][stage]}`}
function seek(p){scrollTo({top:p*($('#experience').offsetHeight-innerHeight),behavior:'instant'});update()}
for(const btn of document.querySelectorAll('[data-path]'))btn.addEventListener('click',()=>{path=btn.dataset.path;document.querySelectorAll('[data-path]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const intent={build:'build_new',finish:'finish_build',automate:'automate_business'}[path];$('#cta').href=window.fsaiAttribution?.appendToUrl(`/fit-check/?intent=${intent}`)||`/fit-check/?intent=${intent}`;copy();scene?.set(progress,path)});
$('#timeline').addEventListener('input',e=>seek(e.target.value/1000));$('#next').addEventListener('click',()=>seek(Math.min(1,(stage+1)/5+.025)));$('#previous').addEventListener('click',()=>seek(Math.max(0,(stage-1)/5+.025)));
async function mode(){const id=++loading,started=performance.now();scene?.dispose();scene=null;document.body.classList.remove('webgl');$('#motion').textContent=staticMode?'Enable 3D view':'Use static view';if(staticMode)return;try{const {createFoundry}=await import('./scene.js');if(id!==loading)return;scene=createFoundry($('#world'),{tier,started,onSlow(){if(selected==='auto'&&tier!=='lite'){tier='lite';setTimeout(()=>{if(id===loading)mode()},0)}}});scene.set(progress,path);document.body.classList.add('webgl')}catch{staticMode=true;$('#motion').textContent='Retry 3D view';$('#status').textContent='3D unavailable. Static view and all experience controls remain available.'}}
$('#motion').addEventListener('click',()=>{staticMode=!staticMode;if(!staticMode&&selected==='static'){selected='auto';tier=initialTier();$('#quality').value='auto'}mode()});motionQuery.addEventListener('change',e=>{staticMode=e.matches;mode()});addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();mode();

$('#quality').addEventListener('change',e=>{selected=e.target.value;staticMode=selected==='static';tier=selected==='auto'?initialTier():Object.hasOwn(TIERS,selected)?selected:tier;mode()});
